### ISSUE TITLE
Failed to install via npm

### ISSUE THREAD

**Issue by MintyMods** [Safort/svelte-dnd#2]
Get the following error while trying to install using  `npm i -S svelte-dnd`

```
$  npm i -S svelte-dnd

> svelte-dnd@0.0.8 postinstall E:\Development\mintysensorserver\node_modules\svelte-dnd
> npm run build


> svelte-dnd@0.0.8 build E:\Development\mintysensorserver\node_modules\svelte-dnd
> cross-env NODE_ENV=production rollup -c

'rollup' is not recognized as an internal or external command,
operable program or batch file.
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: spawn rollup ENOENT
    at notFoundError (E:\Development\MintySensorServer\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (E:\Development\MintySensorServer\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (E:\Development\MintySensorServer\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
Emitted 'error' event at:
    at ChildProcess.cp.emit (E:\Development\MintySensorServer\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn rollup',
  path: 'rollup',
  spawnargs: [ '-c' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-dnd@0.0.8 build: `cross-env NODE_ENV=production rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-dnd@0.0.8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Minty\AppData\Roaming\npm-cache\_logs\2019-10-16T02_27_03_435Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-dnd@0.0.8 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-dnd@0.0.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Safort** [comment]
Thank you for feedback. I'll check it on weekend.

**Comment by Safort** [comment]
Fixed.
